import type { ChangeEvent } from 'react'
import type { Design } from '../../api/designs'
import type { PieceType } from '../../api/piece-types'

export interface InventoryFilterValues { designId: string; pieceTypeId: string; lifecycleStatus: string; condition: string; storageLocation: string; measurementDefinitionId: string; measurementMin: string; measurementMax: string }
export default function InventoryFilters({ value, designs, pieceTypes, onChange, onReset }: { value: InventoryFilterValues; designs: Design[]; pieceTypes: PieceType[]; onChange: (next: InventoryFilterValues) => void; onReset: () => void }) {
  const change = (event: ChangeEvent<HTMLSelectElement | HTMLInputElement>) => onChange({ ...value, [event.target.name]: event.target.value })
  return <section className="inventory-filters" aria-label="Inventory filters"><label>Design<select name="designId" value={value.designId} onChange={change}><option value="">All designs</option>{designs.map((design) => <option key={design.id} value={design.id}>{design.designCode} — {design.name}</option>)}</select></label><label>Piece type<select name="pieceTypeId" value={value.pieceTypeId} onChange={change}><option value="">All piece types</option>{pieceTypes.map((piece) => <option key={piece.id} value={piece.id}>{piece.code} — {piece.name}</option>)}</select></label><label>Lifecycle<select name="lifecycleStatus" value={value.lifecycleStatus} onChange={change}><option value="">All lifecycle states</option>{['ACTIVE', 'CLEANING', 'REPAIR_REQUIRED', 'ALTERATION_REQUIRED', 'MISSING', 'RETIRED'].map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label><label>Condition<select name="condition" value={value.condition} onChange={change}><option value="">All conditions</option>{['NEW', 'EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED'].map((status) => <option key={status} value={status}>{status}</option>)}</select></label><label>Storage location<input name="storageLocation" value={value.storageLocation} onChange={change} /></label><label>Measurement definition<input name="measurementDefinitionId" value={value.measurementDefinitionId} onChange={change} /></label><label>Minimum measurement<input name="measurementMin" inputMode="decimal" value={value.measurementMin} onChange={change} /></label><label>Maximum measurement<input name="measurementMax" inputMode="decimal" value={value.measurementMax} onChange={change} /></label><button type="button" className="button button-secondary" onClick={onReset}>Clear filters</button></section>
}
