import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiError } from '../api/designs'
import { createInventoryItem } from '../api/inventory'
import { listOriginalSets, type OriginalSetSummary } from '../api/original-sets'
import { listMeasurementDefinitions, listPieceTypes, type MeasurementDefinition, type PieceType } from '../api/piece-types'
import PageHeader from '../components/app/PageHeader'
import ErrorBanner from '../components/feedback/ErrorBanner'
import LoadingState from '../components/feedback/LoadingState'

export default function InventoryCreate() {
  const navigate = useNavigate(); const [sets, setSets] = useState<OriginalSetSummary[]>([]); const [types, setTypes] = useState<PieceType[]>([]); const [definitions, setDefinitions] = useState<MeasurementDefinition[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ originalSetId: '', pieceTypeId: '', pieceSequence: '1', customSize: '', condition: 'GOOD', storageLocation: '', notes: '', measurements: {} as Record<string, string> })
  useEffect(() => { let active = true; void Promise.all([listOriginalSets(), listPieceTypes()]).then(([originalSets, pieceTypes]) => { if (active) { setSets(originalSets.filter((set) => !set.archivedAt && !set.verifiedAt)); setTypes(pieceTypes.filter((piece) => piece.active)) } }).catch((reason) => active && setError(apiError(reason).message)).finally(() => active && setLoading(false)); return () => { active = false } }, [])
  useEffect(() => { if (!form.pieceTypeId) { setDefinitions([]); return }; let active = true; void listMeasurementDefinitions(form.pieceTypeId).then((next) => { if (active) setDefinitions(next.filter((definition) => definition.active)) }).catch((reason) => active && setError(apiError(reason).message)); return () => { active = false } }, [form.pieceTypeId])
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const created = await createInventoryItem({ originalSetId: form.originalSetId, pieceTypeId: form.pieceTypeId, pieceSequence: Number(form.pieceSequence), customSize: form.customSize || null, condition: form.condition, storageLocation: form.storageLocation || null, notes: form.notes || null, measurements: definitions.flatMap((definition) => form.measurements[definition.id] ? [{ measurementDefinitionId: definition.id, value: form.measurements[definition.id] }] : []) }); navigate(`/inventory/${created.inventoryCode}`) } catch (reason) { setError(apiError(reason).message) } finally { setSaving(false) } }
  if (loading) return <LoadingState label="Loading inventory identity choices" />
  return <><PageHeader title="Add inventory" /><section className="inventory-page"><p>Identity is permanent after creation.</p>{error ? <ErrorBanner message={error} /> : null}<form className="editor-form inventory-form" onSubmit={submit}><div className="editor-fields"><label>Original set<select required value={form.originalSetId} onChange={(event) => setForm({ ...form, originalSetId: event.target.value })}><option value="">Choose original set</option>{sets.map((set) => <option value={set.id} key={set.id}>{set.originalSetCode}</option>)}</select></label><label>Piece type<select required value={form.pieceTypeId} onChange={(event) => setForm({ ...form, pieceTypeId: event.target.value, measurements: {} })}><option value="">Choose piece type</option>{types.map((piece) => <option value={piece.id} key={piece.id}>{piece.code} — {piece.name}</option>)}</select></label><label>Piece sequence<input required type="number" min="1" value={form.pieceSequence} onChange={(event) => setForm({ ...form, pieceSequence: event.target.value })} /></label>{definitions.map((definition) => <label key={definition.id}>{definition.label} ({definition.code})<input required={definition.requiredForItem} inputMode="decimal" value={form.measurements[definition.id] ?? ''} onChange={(event) => setForm({ ...form, measurements: { ...form.measurements, [definition.id]: event.target.value } })} /></label>)}<label>Custom size<input value={form.customSize} onChange={(event) => setForm({ ...form, customSize: event.target.value })} /></label><label>Condition<select value={form.condition} onChange={(event) => setForm({ ...form, condition: event.target.value })}>{['NEW', 'EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED'].map((condition) => <option key={condition}>{condition}</option>)}</select></label><label>Storage location<input value={form.storageLocation} onChange={(event) => setForm({ ...form, storageLocation: event.target.value })} /></label><label>Notes<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div><button className="button" disabled={saving}>{saving ? 'Creating…' : 'Create inventory item'}</button></form></section></>
}
